source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'mysql2'
gem 'jquery-rails'
gem 'dynamic_form'
gem 'will_paginate'
gem 'authlogic'
gem 'mail'
gem 'delayed_job'
gem 'aws-s3'
gem 'rmagick'
gem 'delayed_paperclip'
gem 'remotipart'
