development:
  adapter: mysql2
  encoding: utf8
  database: shareonit
  pool: 5
  username: shareonit
  password: share.onit!

test:
  adapter: mysql2
  encoding: utf8
  database: shareonit
  pool: 5
  username: shareonit
  password: share.onit!

production:
  adapter: mysql2
  encoding: utf8
  database: shareonit
  pool: 5
  username: shareonit
  password: share.onit!